name: guiautomotriz_mobile
description: App móvil para gestión automotriz. Consume API REST (NestJS).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  flutter_riverpod: ^2.5.1

  # HTTP
  dio: ^5.4.3+1

  # Navegación
  go_router: ^14.2.0

  # Tokens JWT seguros
  flutter_secure_storage: ^9.2.2

  # Manejo funcional de errores
  dartz: ^0.10.1

  # Comparación de objetos
  equatable: ^2.0.5

  # Internacionalización y formateo
  intl: ^0.19.0

  # Utilidades de UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1

  # Geolocalización
  geolocator: ^11.0.0
  image_picker: ^1.2.3
  socket_io_client: ^3.1.6
  url_launcher: ^6.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  sign_in_with_apple: ^8.1.0
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.2.0
  flutter_svg: ^2.3.0
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_icon_zoom.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_splash.png
  android_12:
    color: "#ffffff"
    image: assets/images/logo_icon_zoom.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/logo.png
    - assets/images/logo_icon.png
    - assets/images/logo_icon_zoom.png
    - assets/images/vehicles/
    - assets/images/vehicles/v2/
    - assets/images/categories/
